[package]
name = "feature"
version = "0.1.0"
authors = ["bindo123"]
edition = "2018"


[features]
some_condition = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
