[package]
name = "exp"
version = "0.1.0"
authors = ["bindo123"]
edition = "2018"
default-run="exp"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
