[package]
name = "cookies"
version = "0.1.0"
authors = ["bindo123"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gotham = { path = "../gotham" }
mime = "0.3"
cookie = "0.15"